apiVersion: apps/v1
kind: Deployment
metadata:
  name: thein-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - name: nginx-2
          image: public.ecr.aws/nginx/nginx:1.21
          command:
          - bash
          - "-c"
          - |
            set -ex
            sed -i 's/80;/8081;/g' /etc/nginx/conf.d/default.conf
            /docker-entrypoint.sh "nginx" "-g" "daemon off;"
          ports:
            - name: tcp
              containerPort: 8081
